name: 'PR Management'

on:
  pull_request:
    types: [ 'opened', 'edited', 'synchronize', 'ready_for_review', 'reopened' ]
    branches: [ 'master' ]

concurrency:
  group: '${{ github.head_ref || github.ref }}-${{ github.workflow }}'
  cancel-in-progress: true

permissions: write-all

jobs:
  validate-pr-title:
    name: 'Validate & Label PR'
    runs-on: [ 'ubuntu-latest' ]
    timeout-minutes: 5
    steps:
      - name: 'Generate App Token'
        uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b # v2.1.1
        id: generate-token
        with:
          app-id: ${{ secrets.DEV_APP_ID}}
          private-key: ${{ secrets.DEV_APP_PRIVATE_KEY }}
      - name: "Check PR Title"
        id: lint_pr_title
        uses: amannn/action-semantic-pull-request@fdd4d3ddf614fbcd8c29e4b106d3bbe0cb2c605d # v6.0.1
        with:
          wip: true
          types: |
            feat
            fix
            ci
            chore
            docs
            test
            style
            refactor
            perf
          requireScope: false
          subjectPattern: ^([A-Z]).+$
          subjectPatternError: |
            The subject
            "{subject}"
            found in the pull request title
            "{title}"
            didn't match the configured pattern. Please ensure that the subject starts with an uppercase character.
            Example:
            feat(ui): Add `Button` component
            ^    ^    ^
            |    |    |__ Subject
            |    |_______ Scope
            |____________ Type
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
      - name: "Add PR comment"
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2.9.4
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        with:
          header: 'pr-title-lint-error'
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          message: |
            Ayo, @${{ github.actor }}! 🚨

            Your pull request title does not follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your title should be adjusted.
            You can check configuration [here](https://github.com/SellPander/MinotiV2/blob/master/.github/workflows/pr-management.yml).

            Details:
            ${{ steps.lint_pr_title.outputs.error_message }}
      - name: "Remove PR comment"
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2.9.4
        if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        with:
          header: 'pr-title-lint-error'
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          delete: true